"""Make username case-insensitive but store with case

Revision ID: 107658b8bbee
Revises: 9660a1d978dd
Create Date: 2025-12-07 15:38:30.152574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107658b8bbee'
down_revision: Union[str, Sequence[str], None] = '9660a1d978dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username_lower', table_name='users')
    # ### end Alembic commands ###
