"""Add auth user

Revision ID: 186f90aef183
Revises: 0378c40d374e
Create Date: 2025-09-22 22:44:40.725999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "186f90aef183"
down_revision: Union[str, Sequence[str], None] = "0378c40d374e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_contacts_user_id",
        "contacts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_contacts_user_id", "contacts", type_="foreignkey")
    op.drop_column("contacts", "user_id")
    op.drop_table("users")
