"""Make email case-insensitive and stored in lowercase

Revision ID: 9660a1d978dd
Revises: ab8d77801a66
Create Date: 2025-12-07 15:20:59.333862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9660a1d978dd'
down_revision: Union[str, Sequence[str], None] = 'ab8d77801a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_email_lower', table_name='users')
    # ### end Alembic commands ###
